INFO:flet_runtime:Assets path configured: D:\ProjectsProgramming\Ivy\app\assets
INFO:flet_runtime:Starting up TCP server on localhost:52523
INFO:flet_runtime:Flet app has started...
INFO:flet_runtime:App session started
INFO:pymorphy3.opencorpora_dict.wrapper:Loading dictionaries from d:\projectsprogramming\ivy\venv\lib\site-packages\pymorphy3_dicts_ru\data
INFO:pymorphy3.opencorpora_dict.wrapper:format: 2.4, revision: 417150, updated: 2022-01-08T22:09:24.565962
INFO:pymorphy3.opencorpora_dict.wrapper:Loading dictionaries from d:\projectsprogramming\ivy\venv\lib\site-packages\pymorphy3_dicts_ru\data
INFO:pymorphy3.opencorpora_dict.wrapper:format: 2.4, revision: 417150, updated: 2022-01-08T22:09:24.565962
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-18' coro=<Equalizer.active_equalizer() done, defined at D:\ProjectsProgramming\Ivy\app\equalizer.py:110> exception=ValueError('buffer size must be a multiple of element size')>
Traceback (most recent call last):
  File "D:\ProjectsProgramming\Ivy\app\equalizer.py", line 113, in active_equalizer
    await self.equalizer_click()
  File "D:\ProjectsProgramming\Ivy\app\equalizer.py", line 168, in equalizer_click
    signal = np.frombuffer(self.equalizer_data_to_vizualize, dtype=np.int32)
ValueError: buffer size must be a multiple of element size
